# THis file is used to clean the similarity file generated by the plagiarism detector
# Keep only the pairs of functions with the same name that have a similarity score above a threshold
# Prevent min / max functions from being compared for instance, but reduce the number of pair when
# students made a mistake in the function name
# The output file is a csv file with the following format:
# team1, team2, function_name, similarity_score
# The output is symetric, so if team1 is compared to team2, team2 is also compared to team1
# usage: python cleanSimilarity.py -s <similarity_file_name> -o <output_folder> -t <threshold>

import csv
import os

from pandas.core.frame import DataFrame
import getopt
import sys

# return the tuple team_name, function_name from a file path
# file name format is team_name.function_name.c


def get_team_function_name(file_path):
    file_name = os.path.basename(file_path)
    team_name = file_name.split(".")[0]
    function_name = file_name.split(".")[1]
    return team_name, function_name


def clean_similarity_file(similarity_file_name, output_folder, threshold):
    csv_data = [["team1", "team2", "function1", "similarity"]]

    with open(similarity_file_name, "r") as similarity_file:
        reader = csv.DictReader(similarity_file)
        for row in reader:
            if float(row["similarity"]) > threshold:
                team_left, function_name_left = get_team_function_name(
                    row["leftFilePath"])
                team_right, function_name_right = get_team_function_name(
                    row["rightFilePath"])
                # only keep the pairs of functions with the same name
                if function_name_left == function_name_right:
                    # add two rows to the csv file, one for each team
                    csv_data.append(
                        [team_left, team_right, function_name_left, row["similarity"]])
                    csv_data.append(
                        [team_right, team_left, function_name_left, row["similarity"]])

    dataframe = DataFrame(csv_data)
    dataframe.to_csv(os.path.join(output_folder, "cleaned_similarity.csv"),
                     index=False, header=False)


# use getopt to parse command line arguments and call clean_similarity_file
# with the correct arguments (similarity_file_name, output_folder, threshold)
if __name__ == "__main__":
    opts, args = getopt.getopt(sys.argv[1:], "s:o:t:")
    similarity_file_name = ""
    output_folder = ""
    threshold = 0.0
    for opt, arg in opts:
        if opt == "-s":
            similarity_file_name = arg
        elif opt == "-o":
            output_folder = arg
        elif opt == "-t":
            threshold = float(arg)
    clean_similarity_file(similarity_file_name, output_folder, threshold)
